eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
    healthcheck:
      enabled: true
server:
  port: 8002
spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 1000000
      max-request-size: 1000000
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  eureka:
   enable: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
hystrix:
  command:
  default:
    execution:
    isolation:
      thread:
      timeoutInMilliseconds: 60000


